name: Salesforce SFDX CLI Action
# You may pin to the exact commit or the version.
# uses: sfdx-actions/setup-sfdx@3e61d1cebdf852470c40c167b5a07952f847a803
  uses: sfdx-actions/setup-sfdx@v1
  with:
   # Authorize a Salesforce org using an SFDX auth URL
    sfdx-auth-url: # optional
